---
title: "ranshen's small house"
date: 2022-05-12
---
title: Your awesome title
author: ranshen-tech
email: ranshen0519@icoud.com
description: > # this means to ignore newlines until "baseurl:"
  hahahahhahahðŸ¥°ðŸ¥° You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
